server:
  port: 8002

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-bp16sp50f69t2jx97jo.mysql.rds.aliyuncs.com:3306/db2019?useUnicode=true&characterEncoding=utf8
    username: hyt1890
    password: Aa490538846
  application:
    name: could-payment-service

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hyt.springcloud.entities

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # 集群版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: payment8002
    prefer-ip-address: true #显示ip地址
